person:
  name:
    - tom
    - jerry
    - mark
  age: 18
  email: 684723@qq.com
  param:
    cell-phone: 16689562356
    address: guizhou
  configKey:
    privateKey: fjsalfjlasf
    publicKey: fjkasfkdahskfdjskdf

cat:
  name: 小黑
  age: 2
  color: black
  birthday: 2022-02-06 15:23:45

member:
  name: 李四
  age: 19
  height: 180

car:
  name: 花豆
  age: 4
  color: black

javastack:
  username: ENC@[WtpACDLXPkiyvfy35dqpPwVoYMNg8PKNq8mSejuKsEjzJFEQKFH+HNKYD3eakcB1]
  password: ENC@[ZpsZTBijC5Y2wKDrRvlLCqgMsiinT4AnpUWDBRghhev2B17GLgEwzmnfWvg6zABL]

