spring:
  application:
    name: config-manage
  profiles:
    default: dev
    active: dev

  mail:
    host: smtp.qq.com
    username: 2625895245@qq.com
#    password: hmwavgvqpupodice
    password: ENC@[dJjbVKLRbAMlIObQmvqOipE8OSMGUvlYlbwTG1Z1m7WwmXcK2ErzTtc9t6Vb6JDd/1JlUrnlV8TRIKn2B9B2Zw==] # 加密授权码
    defaultEncoding: UTF-8
    properties:
      "[mail.smtp.socketFactory.class]": javax.net.ssl.SSLSocketFactory
      "[mail.smtp.socketFactory.fallback]": false
      "[mail.smtp.socketFactory.port]": 465
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000

# 邮件
mail:
  from: 2625895245@qq.com
  personal: 栈长
  bcc: 2625895245@qq.com  # bcc:含义"密送", 在同时向多个人发送邮件时, 可以使接收者不知道你还发给了谁
  subject: Spring Boot 发送邮件测试主题

jasypt:
  encryptor:
    password: fkjHKJHKfs435jhfkjdahfaksldfhkajfhjs
    property:
      prefix: "ENC@["
      suffix: "]"




